# CLI Tools
brew "htop"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "gh"

brew "node"
brew "pnpm"

# Install fonts
cask "font-fira-code-nerd-font"

# User Interfaces
cask "spotify"
cask "discord"
cask "firefox"
cask "obsidian"
cask "signal"
cask "aftman"
